[build]
publish = "dist/"
command = "yarn build"

[build.environment]
# Build Previews
NODE_ENV = "production"
YARN_FLAGS = "--production=false"
NETLIFY_USE_YARN = true
VUE_APP_API_URL = "https://predict-to-win.herokuapp.com"

[context.production.environment]
VUE_APP_API_URL = "https://predict-to-win.herokuapp.com"

# Redirect rule for compatibility with Vue Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
